## 여러 시리즈로 데이터프레임 생성

In [ ]:
import pandas as pd

courses = pd.Series(["Spark", "PySpark", "Handoop"], name = 'course')
courses

0      Spark
1    PySpark
2    Handoop
Name: course, dtype: object

In [ ]:
fees = pd.Series([250000, 300000, 200000], name='fees')
fees

0    250000
1    300000
2    200000
Name: fees, dtype: int64

In [ ]:
df = pd.DataFrame({courses.name: courses, fees.name: fees})
df

    course    fees
0    Spark  250000
1  PySpark  300000
2  Handoop  200000

In [ ]:
courses = pd.Series(["Spark", "PySpark", "Handoop"], name='courses')
fees=pd.Series([250000,300000,200000], name='fees')

df = pd.concat([courses,fees], axis=1)
df

   courses    fees
0    Spark  250000
1  PySpark  300000
2  Handoop  200000

In [ ]:
courses = pd.Series(["Spark", "PySpark", "Handoop"], name='courses')
fees=pd.Series([250000,300000,200000], name='fees')

df=pd.concat([courses, fees])
df

0      Spark
1    PySpark
2    Handoop
0     250000
1     300000
2     200000
dtype: object

In [ ]:
df = pd.DataFrame([{'국어': 70, '수학':89, '영어':90},
                  {'국어': 80, '영어':90},
                  {'수학':60, '영어':78}])
df

     국어    수학  영어
0  70.0  89.0  90
1  80.0   NaN  90
2   NaN  60.0  78

In [ ]:
s1 = pd.Series([90,80,60,66])
s2 = pd.Series([45,73,83,99])
s3 = pd.Series([92,75,82,75])
s1

0    90
1    80
2    60
3    66
dtype: int64

In [ ]:
df = pd.DataFrame({'국어':s1, '영어':s2, '수학':s3})
df

   국어  영어  수학
0  90  45  92
1  80  73  75
2  60  83  82
3  66  99  75

In [ ]:
df.index = ['노', '장', '박', '강']
df

   국어  영어  수학
노  90  45  92
장  80  73  75
박  60  83  82
강  66  99  75

In [ ]:
df = pd.DataFrame({'A': pd.Series([10,20,30], index=[0,1,2]),
                   'B': pd.Series([3,2,1], index=[1,2,3])})
df

      A    B
0  10.0  NaN
1  20.0  3.0
2  30.0  2.0
3   NaN  1.0

In [ ]:
s1 = pd.Series([90,80,60], index=['노', '장', '박'])
s2 = pd.Series([45,73,99], index = ['장', '박', '강'])
s3 = pd.Series([92, 75, 82, 75])

In [ ]:
df = pd.DataFrame ({'국어':s1, '영어':s2, '수학':s3},
                   index = ['노', '장', '박', '강'])
df

     국어    영어  수학
노  90.0   NaN NaN
장  80.0  45.0 NaN
박  60.0  73.0 NaN
강   NaN  99.0 NaN

In [ ]:
d = {'col1':[1,2], 'col2':[3,4 ]}
df = pd.DataFrame(data=d)
df

   col1  col2
0     1     3
1     2     4

In [ ]:
df.dtypes

col1    int64
col2    int64
dtype: object

In [ ]:
import numpy as np

df=pd.DataFrame(data=d, dtype = np.int8)
df.dtypes

col1    int8
col2    int8
dtype: object

In [ ]:
d = {'col1': [1, 2], 'col2': [3, 4]}
df = pd.DataFrame(data=d)
df

   col1  col2
0     1     3
1     2     4

In [ ]:
df = pd.DataFrame(data=d, dtype=np.int8)
df.dtypes

col1    int8
col2    int8
dtype: object

In [ ]:
dates = pd.date_range("20250202", periods = 6, freq='W-TUE')
dates

DatetimeIndex(['2025-02-04', '2025-02-11', '2025-02-18', '2025-02-25',
               '2025-03-04', '2025-03-11'],
              dtype='datetime64[ns]', freq='W-TUE')

In [ ]:
dates = pd.date_range("20250202", periods = 6, freq='W-FRI')
dates

DatetimeIndex(['2025-02-07', '2025-02-14', '2025-02-21', '2025-02-28',
               '2025-03-07', '2025-03-14'],
              dtype='datetime64[ns]', freq='W-FRI')

In [ ]:
dates = pd.date_range("20250202", periods = 6, freq='M')
dates

/tmp/ipykernel_26441/592317253.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  dates = pd.date_range("20250202", periods = 6, freq='M')

DatetimeIndex(['2025-02-28', '2025-03-31', '2025-04-30', '2025-05-31',
               '2025-06-30', '2025-07-31'],
              dtype='datetime64[ns]', freq='ME')

In [ ]:
dates = pd.date_range("20250202", periods = 6, freq='MS')
dates

DatetimeIndex(['2025-03-01', '2025-04-01', '2025-05-01', '2025-06-01',
               '2025-07-01', '2025-08-01'],
              dtype='datetime64[ns]', freq='MS')

In [ ]:
df2 = pd.DataFrame({
    "A": 1.0,
    "B": pd.Timestamp("20260302"),
    "C": pd.Series(np.arange(1, 3, .5)),
    "D": np.array([3] * 4, dtype="int32"),
    "E": pd.Categorical(["test", "train", "test", "train"]),
    "F": "foo"
})

df2

     A          B    C  D      E    F
0  1.0 2026-03-02  1.0  3   test  foo
1  1.0 2026-03-02  1.5  3  train  foo
2  1.0 2026-03-02  2.0  3   test  foo
3  1.0 2026-03-02  2.5  3  train  foo

In [ ]:
df2.dtypes

A          float64
B    datetime64[s]
C          float64
D            int32
E         category
F           object
dtype: object

In [ ]:
import pandas as pd

pf = pd.DataFrame(data = [[25,35,8,18],
                          [18,27,10,20],
                          [17,17,10,19],
                          [12,22,9,20],
                          [22,34,8,16]],
                  index = ['윤일형', '강수희', '홍소희', '유한빈', '신수빈'],

                  columns=['중간', '기말', '과제', '출석'])

In [ ]:
pf['중간']

윤일형    25
강수희    18
홍소희    17
유한빈    12
신수빈    22
Name: 중간, dtype: int64

In [ ]:
pf['출석']

윤일형    18
강수희    20
홍소희    19
유한빈    20
신수빈    16
Name: 출석, dtype: int64

In [ ]:
pf[['출석']]

     출석
윤일형  18
강수희  20
홍소희  19
유한빈  20
신수빈  16

In [ ]:
pf[['기말', '출석', '중간']]

     기말  출석  중간
윤일형  35  18  25
강수희  27  20  18
홍소희  17  19  17
유한빈  22  20  12
신수빈  34  16  22

In [ ]:
pf[['기말']]

     기말
윤일형  35
강수희  27
홍소희  17
유한빈  22
신수빈  34

In [ ]:
pf

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

In [ ]:
pf['중간']>20

윤일형     True
강수희    False
홍소희    False
유한빈    False
신수빈     True
Name: 중간, dtype: bool

In [ ]:
pf[pf['중간']>20]

     중간  기말  과제  출석
윤일형  25  35   8  18
신수빈  22  34   8  16

In [ ]:
pf[pf['출석']>=19]

     중간  기말  과제  출석
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20

In [ ]:
pf[(pf['출석']>=19) & (pf['기말'] >= 20)]

     중간  기말  과제  출석
강수희  18  27  10  20
유한빈  12  22   9  20

In [ ]:
pf.loc['윤일형']

중간    25
기말    35
과제     8
출석    18
Name: 윤일형, dtype: int64

In [ ]:
pf.loc[['윤일형']]

     중간  기말  과제  출석
윤일형  25  35   8  18

In [ ]:
pf.loc[['홍소희', '윤일형']]

     중간  기말  과제  출석
홍소희  17  17  10  19
윤일형  25  35   8  18

In [ ]:
pf.loc['윤일형':'유한빈']

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20

In [ ]:
pf.loc[pf.중간>20]

     중간  기말  과제  출석
윤일형  25  35   8  18
신수빈  22  34   8  16

In [ ]:
pf.loc[(pf.중간>10) & (pf.과제 == 10)]

     중간  기말  과제  출석
강수희  18  27  10  20
홍소희  17  17  10  19

In [ ]:
pf.loc[pf.index[0]]

중간    25
기말    35
과제     8
출석    18
Name: 윤일형, dtype: int64

In [ ]:
pf.loc[[pf.index[0]]]

     중간  기말  과제  출석
윤일형  25  35   8  18

In [ ]:
pf.loc[pf.index[1:4]]

     중간  기말  과제  출석
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20

In [ ]:
pf.loc[pf.index[1:4]][['기말', '과제']]

     기말  과제
강수희  27  10
홍소희  17  10
유한빈  22   9

In [ ]:
pf.loc[:,'과제']

윤일형     8
강수희    10
홍소희    10
유한빈     9
신수빈     8
Name: 과제, dtype: int64

In [ ]:
pf.loc[:, '중간':'과제']

     중간  기말  과제
윤일형  25  35   8
강수희  18  27  10
홍소희  17  17  10
유한빈  12  22   9
신수빈  22  34   8

In [ ]:
pf.loc[:, ['기말', '출석']]

     기말  출석
윤일형  35  18
강수희  27  20
홍소희  17  19
유한빈  22  20
신수빈  34  16

In [ ]:
pf.loc[:, pf.columns[0]]

윤일형    25
강수희    18
홍소희    17
유한빈    12
신수빈    22
Name: 중간, dtype: int64

In [ ]:
pf.loc[:, [pf.columns[0]]]

     중간
윤일형  25
강수희  18
홍소희  17
유한빈  12
신수빈  22

In [ ]:
pf.loc[:, pf.columns[1:]]

     기말  과제  출석
윤일형  35   8  18
강수희  27  10  20
홍소희  17  10  19
유한빈  22   9  20
신수빈  34   8  16

In [ ]:
pf.loc[:, pf.columns[1:3]]

     기말  과제
윤일형  35   8
강수희  27  10
홍소희  17  10
유한빈  22   9
신수빈  34   8

In [ ]:
pf.loc[:, pf.columns[1:]][['기말', '과제']]

     기말  과제
윤일형  35   8
강수희  27  10
홍소희  17  10
유한빈  22   9
신수빈  34   8

In [ ]:
pf.loc['윤일형','출석']

np.int64(18)

In [ ]:
pf.loc['윤일형':'유한빈', '기말']

윤일형    35
강수희    27
홍소희    17
유한빈    22
Name: 기말, dtype: int64

In [ ]:
pf.loc['윤일형':'유한빈', '기말':'과제']

     기말  과제
윤일형  35   8
강수희  27  10
홍소희  17  10
유한빈  22   9

In [ ]:
pf.iloc[[1]]

     중간  기말  과제  출석
강수희  18  27  10  20

In [ ]:
pf.iloc[[1,3]]

     중간  기말  과제  출석
강수희  18  27  10  20
유한빈  12  22   9  20

In [ ]:
pf.iloc[2:]

     중간  기말  과제  출석
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

In [ ]:
pf.iloc[:,[2]]

     과제
윤일형   8
강수희  10
홍소희  10
유한빈   9
신수빈   8

In [ ]:
pf.iloc[:, 1:]

     기말  과제  출석
윤일형  35   8  18
강수희  27  10  20
홍소희  17  10  19
유한빈  22   9  20
신수빈  34   8  16

In [ ]:
pf.iloc[1:3, 1:]

     기말  과제  출석
강수희  27  10  20
홍소희  17  10  19

In [ ]:
pf.iloc[[1,3,4], 1:]

     기말  과제  출석
강수희  27  10  20
유한빈  22   9  20
신수빈  34   8  16

In [ ]:
import pandas as pd

df = pd.read_csv('2016년졸음운전.csv', encoding='euc-kr', index_col=0)

df

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     174      6    328
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년9월     187     13    347
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

In [ ]:
df.dtypes

사고(건)    int64
사망(명)    int64
부상(명)    int64
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12 entries, 2016년1월 to 2016년12월
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   사고(건)   12 non-null     int64
 1   사망(명)   12 non-null     int64
 2   부상(명)   12 non-null     int64
dtypes: int64(3)
memory usage: 384.0+ bytes

In [ ]:
df.describe()

            사고(건)      사망(명)       부상(명)
count   12.000000  12.000000   12.000000
mean   202.750000   8.166667  408.250000
std     23.014324   3.186144   60.051682
min    168.000000   4.000000  328.000000
25%    186.000000   5.750000  363.500000
50%    200.000000   7.000000  402.500000
75%    219.500000  10.500000  441.250000
max    239.000000  13.000000  522.000000

In [ ]:
df.sum()

사고(건)    2433
사망(명)      98
부상(명)    4899
dtype: int64

In [ ]:
df.sum(axis=0)

사고(건)    2433
사망(명)      98
부상(명)    4899
dtype: int64

In [ ]:
df.sum(axis=1)

연월
2016년1월     584
2016년2월     508
2016년3월     659
2016년4월     642
2016년5월     774
2016년6월     574
2016년7월     696
2016년8월     727
2016년9월     547
2016년10월    560
2016년11월    623
2016년12월    536
dtype: int64

In [ ]:
df.cumsum(axis=0)

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     366     11    715
2016년3월     583     18   1150
2016년4월     799     25   1569
2016년5월    1038     38   2091
2016년6월    1238     50   2453
2016년7월    1465     59   2913
2016년8월    1695     66   3403
2016년9월    1882     79   3750
2016년10월   2065     89   4117
2016년11월   2265     94   4535
2016년12월   2433     98   4899

In [ ]:
df.cumsum(axis=1)

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192    197    584
2016년2월     174    180    508
2016년3월     217    224    659
2016년4월     216    223    642
2016년5월     239    252    774
2016년6월     200    212    574
2016년7월     227    236    696
2016년8월     230    237    727
2016년9월     187    200    547
2016년10월    183    193    560
2016년11월    200    205    623
2016년12월    168    172    536

In [ ]:
df.mean()

사고(건)    202.750000
사망(명)      8.166667
부상(명)    408.250000
dtype: float64

In [ ]:
df.mean(axis=0)

사고(건)    202.750000
사망(명)      8.166667
부상(명)    408.250000
dtype: float64

In [ ]:
df.mean(axis=1)

연월
2016년1월     194.666667
2016년2월     169.333333
2016년3월     219.666667
2016년4월     214.000000
2016년5월     258.000000
2016년6월     191.333333
2016년7월     232.000000
2016년8월     242.333333
2016년9월     182.333333
2016년10월    186.666667
2016년11월    207.666667
2016년12월    178.666667
dtype: float64

In [ ]:
df.mean(axis=None)

np.float64(206.38888888888889)

In [ ]:
df.max()

사고(건)    239
사망(명)     13
부상(명)    522
dtype: int64

In [ ]:
df.max(axis=0)

사고(건)    239
사망(명)     13
부상(명)    522
dtype: int64

In [ ]:
df.max(axis=1)

연월
2016년1월     387
2016년2월     328
2016년3월     435
2016년4월     419
2016년5월     522
2016년6월     362
2016년7월     460
2016년8월     490
2016년9월     347
2016년10월    367
2016년11월    418
2016년12월    364
dtype: int64

In [ ]:
df.max(axis=None)

522

In [ ]:
df.min()

사고(건)    168
사망(명)      4
부상(명)    328
dtype: int64

In [ ]:
df.min(axis=0)

사고(건)    168
사망(명)      4
부상(명)    328
dtype: int64

In [ ]:
df.min(axis=1)

연월
2016년1월      5
2016년2월      6
2016년3월      7
2016년4월      7
2016년5월     13
2016년6월     12
2016년7월      9
2016년8월      7
2016년9월     13
2016년10월    10
2016년11월     5
2016년12월     4
dtype: int64

In [ ]:
df[['사망(명)', '부상(명)']].sum(axis=1)

연월
2016년1월     392
2016년2월     334
2016년3월     442
2016년4월     426
2016년5월     535
2016년6월     374
2016년7월     469
2016년8월     497
2016년9월     360
2016년10월    377
2016년11월    423
2016년12월    368
dtype: int64

In [ ]:
df.iloc[:, 1:].sum(axis=1)

연월
2016년1월     392
2016년2월     334
2016년3월     442
2016년4월     426
2016년5월     535
2016년6월     374
2016년7월     469
2016년8월     497
2016년9월     360
2016년10월    377
2016년11월    423
2016년12월    368
dtype: int64

In [ ]:
df2 = df.copy()
df2['재해지수'] = df[['사망(명)', '부상(명)']].sum(axis=1)
df2

          사고(건)  사망(명)  부상(명)  재해지수
연월
2016년1월     192      5    387   392
2016년2월     174      6    328   334
2016년3월     217      7    435   442
2016년4월     216      7    419   426
2016년5월     239     13    522   535
2016년6월     200     12    362   374
2016년7월     227      9    460   469
2016년8월     230      7    490   497
2016년9월     187     13    347   360
2016년10월    183     10    367   377
2016년11월    200      5    418   423
2016년12월    168      4    364   368

In [ ]:
df2.loc['총계'] = df.sum(axis= 0)
df2

           사고(건)  사망(명)   부상(명)   재해지수
연월
2016년1월    192.0    5.0   387.0  392.0
2016년2월    174.0    6.0   328.0  334.0
2016년3월    217.0    7.0   435.0  442.0
2016년4월    216.0    7.0   419.0  426.0
2016년5월    239.0   13.0   522.0  535.0
2016년6월    200.0   12.0   362.0  374.0
2016년7월    227.0    9.0   460.0  469.0
2016년8월    230.0    7.0   490.0  497.0
2016년9월    187.0   13.0   347.0  360.0
2016년10월   183.0   10.0   367.0  377.0
2016년11월   200.0    5.0   418.0  423.0
2016년12월   168.0    4.0   364.0  368.0
총계        2433.0   98.0  4899.0    NaN

In [ ]:
df2 > 10

          사고(건)  사망(명)  부상(명)   재해지수
연월
2016년1월    True  False   True   True
2016년2월    True  False   True   True
2016년3월    True  False   True   True
2016년4월    True  False   True   True
2016년5월    True   True   True   True
2016년6월    True   True   True   True
2016년7월    True  False   True   True
2016년8월    True  False   True   True
2016년9월    True   True   True   True
2016년10월   True  False   True   True
2016년11월   True  False   True   True
2016년12월   True  False   True   True
총계         True   True   True  False

In [ ]:
df2[ [True]*6 + [False]*7]

         사고(건)  사망(명)  부상(명)   재해지수
연월
2016년1월  192.0    5.0  387.0  392.0
2016년2월  174.0    6.0  328.0  334.0
2016년3월  217.0    7.0  435.0  442.0
2016년4월  216.0    7.0  419.0  426.0
2016년5월  239.0   13.0  522.0  535.0
2016년6월  200.0   12.0  362.0  374.0

In [ ]:
df2['재해지수']>400

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월      True
2016년6월     False
2016년7월      True
2016년8월      True
2016년9월     False
2016년10월    False
2016년11월     True
2016년12월    False
총계          False
Name: 재해지수, dtype: bool

In [ ]:
df2[df2['재해지수']>400]

          사고(건)  사망(명)  부상(명)   재해지수
연월
2016년3월   217.0    7.0  435.0  442.0
2016년4월   216.0    7.0  419.0  426.0
2016년5월   239.0   13.0  522.0  535.0
2016년7월   227.0    9.0  460.0  469.0
2016년8월   230.0    7.0  490.0  497.0
2016년11월  200.0    5.0  418.0  423.0

In [ ]:
df['사망(명)'] ==7

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월     False
2016년6월     False
2016년7월     False
2016년8월      True
2016년9월     False
2016년10월    False
2016년11월    False
2016년12월    False
Name: 사망(명), dtype: bool

In [ ]:
df['사망(명)'].isin([7, 10])

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월     False
2016년6월     False
2016년7월     False
2016년8월      True
2016년9월     False
2016년10월     True
2016년11월    False
2016년12월    False
Name: 사망(명), dtype: bool

In [ ]:
df[df['사망(명)'].isin([7, 10])]

          사고(건)  사망(명)  부상(명)
연월
2016년3월     217      7    435
2016년4월     216      7    419
2016년8월     230      7    490
2016년10월    183     10    367

In [ ]:
df[(df['사망(명)'].isin([7,10]))|(df['부상(명)']>350)]

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

In [ ]:
df[df.index.str.contains('3')]

         사고(건)  사망(명)  부상(명)
연월
2016년3월    217      7    435

In [ ]:
df3 = df.copy()
df3

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     174      6    328
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년9월     187     13    347
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

In [ ]:
df3[df3 > 10] = -df3
df3

          사고(건)  사망(명)  부상(명)
연월
2016년1월    -192      5   -387
2016년2월    -174      6   -328
2016년3월    -217      7   -435
2016년4월    -216      7   -419
2016년5월    -239    -13   -522
2016년6월    -200    -12   -362
2016년7월    -227      9   -460
2016년8월    -230      7   -490
2016년9월    -187    -13   -347
2016년10월   -183     10   -367
2016년11월   -200      5   -418
2016년12월   -168      4   -364

In [ ]:
df = pd.DataFrame({'A' : range(1, 6),
                   'B' : range(6, -3, -2),
                   'C' : range(10, 5, -1),
                   'D clmns' : range(3, -2, -1),
                   'E':['python', 'java', 'python', 'go', 'python']})

df

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java
2  3  2   8        1  python
3  4  0   7        0      go
4  5 -2   6       -1  python

In [ ]:
df.query('A>B')

   A  B  C  D clmns       E
2  3  2  8        1  python
3  4  0  7        0      go
4  5 -2  6       -1  python

In [ ]:
df[df.A > df.B]

   A  B  C  D clmns       E
2  3  2  8        1  python
3  4  0  7        0      go
4  5 -2  6       -1  python

In [ ]:
df.query('C == 10')

   A  B   C  D clmns       E
0  1  6  10        3  python

In [ ]:
df.query('A>0')

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java
2  3  2   8        1  python
3  4  0   7        0      go
4  5 -2   6       -1  python

In [ ]:
df.query('E == "python"')

   A  B   C  D clmns       E
0  1  6  10        3  python
2  3  2   8        1  python
4  5 -2   6       -1  python

In [ ]:
df.query('A == " D clmns"')

Empty DataFrame
Columns: [A, B, C, D clmns, E]
Index: []

In [ ]:
df.query('A>3 | 3 > 8')

   A  B  C  D clmns       E
3  4  0  7        0      go
4  5 -2  6       -1  python

In [ ]:
df.query('A > 2 & C < B')

Empty DataFrame
Columns: [A, B, C, D clmns, E]
Index: []

In [ ]:
num = 3
df.query('B > @num')

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java

In [ ]:
num = 3
df.query(f'B > {num}')

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java

In [ ]:
S = "E.str.contains('py')"
df.query(S)

   A  B   C  D clmns       E
0  1  6  10        3  python
2  3  2   8        1  python
4  5 -2   6       -1  python

In [ ]:
s = 'E.str.contains("B")'
df.query(s)

Empty DataFrame
Columns: [A, B, C, D clmns, E]
Index: []

In [ ]:
S = "E.str.contains('on')"
df.query(S)

   A  B   C  D clmns       E
0  1  6  10        3  python
2  3  2   8        1  python
4  5 -2   6       -1  python